# -*- coding: utf-8 -*-
"""Yfinance Demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ursPwR1qeVZP77P-RiivSHEZnuxEn4Bg
"""

# ==============================================================================
# DEMO: HAYALİ KULLANICI ÜRETİMİ VE CANLI BİST 100 PORTFÖY DEĞERLEMESİ
# ==============================================================================

# 1. Gerekli Kütüphanelerin Yüklenmesi
!pip install yfinance faker psycopg2-binary sqlalchemy pandas -q

import random
from faker import Faker
import pandas as pd
import yfinance as yf
from sqlalchemy import create_engine, Column, Integer, String, Float
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker

# --- KONFİGÜRASYON VE BAĞLANTI ---
fake = Faker('tr_TR')

# ⚠️ LÜTFEN KENDİ RENDER POSTGRESQL EXTERNAL URL'İNİ YAZ:
RENDER_EXTERNAL_URL = "postgresql://finans_db_57rk_user:EPkJ3IXyvgHIqUHTmpL11u5ppPZenAvW@dpg-d9td763m8hqs73crb70g-a.frankfurt-postgres.render.com/finans_db_57rk"

engine = create_engine(RENDER_EXTERNAL_URL)
SessionLocal = sessionmaker(bind=engine)
Base = declarative_base()

# --- VERİTABANI MODELLERİ (ORM) ---
class User(Base):
    __tablename__ = "users"
    user_id = Column(String, primary_key=True)
    full_name = Column(String)
    risk_profile = Column(String)
    cash_try = Column(Float)

class Portfolio(Base):
    __tablename__ = "portfolio"
    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String)
    asset_type = Column(String)
    symbol = Column(String)
    quantity = Column(Float)
    avg_cost_try = Column(Float)

# Tabloların veritabanında oluştuğundan emin olalım
Base.metadata.create_all(bind=engine)

# --- 1. ADIM: HAYALİ KULLANICI VE BİST PORTFÖYÜ ÜRETME ---
def generate_demo_user():
    session = SessionLocal()

    # Temiz bir demo için eski verileri sıfırlayalım
    session.query(Portfolio).delete()
    session.query(User).delete()
    session.commit()

    # Sadece BİST 100 Hisse Senetleri
    bist_stocks = [
        ("THYAO.IS", 270.0, 310.0),
        ("GARAN.IS", 85.0, 110.0),
        ("EREGL.IS", 38.0, 50.0),
        ("KCHOL.IS", 200.0, 240.0),
        ("ASELS.IS", 50.0, 65.0),
        ("SISE.IS", 42.0, 55.0),
        ("BIMAS.IS", 450.0, 520.0)
    ]

    user_id = "USR-DEMO-01"
    full_name = fake.name()
    risk_profile = random.choice(["Muhafazakar", "Dengeli", "Agresif"])
    cash_try = round(random.uniform(10000, 75000), 2)

    # Kullanıcı kaydı
    new_user = User(
        user_id=user_id,
        full_name=full_name,
        risk_profile=risk_profile,
        cash_try=cash_try
    )
    session.add(new_user)

    # Kullanıcıya rastgele 3 ile 5 arası farklı BİST hissesi ata
    selected_stocks = random.sample(bist_stocks, k=random.randint(3, 5))

    for symbol, min_cost, max_cost in selected_stocks:
        qty = random.randint(20, 300)
        cost = round(random.uniform(min_cost, max_cost), 2)

        portfolio_item = Portfolio(
            user_id=user_id,
            asset_type="Stock",
            symbol=symbol,
            quantity=qty,
            avg_cost_try=cost
        )
        session.add(portfolio_item)

    session.commit()
    session.close()
    print(f"👤 Hayali Kullanıcı Oluşturuldu: {full_name} ({user_id})")
    print("💾 Kullanıcı ve hisse bilgileri Render PostgreSQL'e kaydedildi.\n")
    return user_id

# --- 2. ADIM: YAHOO FINANCE'DEN CANLI FİYAT ÇEKME ---
def get_live_stock_price(symbol: str) -> float:
    try:
        ticker = yf.Ticker(symbol)
        data = ticker.history(period="1d")
        if not data.empty:
            return round(float(data["Close"].iloc[-1]), 2)
    except Exception as e:
        print(f"⚠️ {symbol} için fiyat çekilemedi: {e}")
    return 0.0

# --- 3. ADIM: PORTFÖYÜ DEĞERLEME VE CANLI RAPORLAMA ---
def run_portfolio_demo(user_id: str):
    session = SessionLocal()

    # Veritabanından Kullanıcı ve Portföy Bilgilerini Okuma
    user = session.query(User).filter(User.user_id == user_id).first()
    portfolio_items = pd.read_sql(f"SELECT * FROM portfolio WHERE user_id = '{user_id}'", con=engine)

    print("🔄 BİST 100 hisselerinin canlı fiyatları Yahoo Finance üzerinden çekiliyor...\n")

    results = []
    total_cost = 0
    total_current_value = 0

    for _, row in portfolio_items.iterrows():
        symbol = row["symbol"]
        qty = row["quantity"]
        cost = row["avg_cost_try"]

        # Canlı Borsa Fiyatı Çekme
        live_price = get_live_stock_price(symbol)
        if live_price == 0.0:
            live_price = cost # Hata durumunda maliyeti koru

        item_cost = qty * cost
        item_value = qty * live_price
        pnl_try = item_value - item_cost
        pnl_pct = ((live_price - cost) / cost) * 100 if cost > 0 else 0

        total_cost += item_cost
        total_current_value += item_value

        results.append({
            "Hisse Sembolü": symbol.replace(".IS", ""), # Temiz görünüm için .IS kaldırıldı
            "Adet": int(qty),
            "Ort. Maliyet (TL)": f"{cost:,.2f}",
            "Canlı Fiyat (TL)": f"{live_price:,.2f}",
            "Toplam Maliyet (TL)": f"{item_cost:,.2f}",
            "Güncel Değer (TL)": f"{item_value:,.2f}",
            "Kâr / Zarar (TL)": f"{pnl_try:+,.2f}",
            "Değişim (%)": f"%{pnl_pct:+.2f}"
        })

    session.close()

    # Toplam Hesaplamalar
    net_pnl = total_current_value - total_cost
    total_pnl_pct = (net_pnl / total_cost) * 100 if total_cost > 0 else 0

    # --- RENDER/TABLO ÇIKTILARI ---
    user_summary_df = pd.DataFrame([{
        "Kullanıcı ID": user.user_id,
        "Ad Soyad": user.full_name,
        "Risk Profili": user.risk_profile,
        "Nakit Bakiye (TL)": f"{user.cash_try:,.2f} TL"
    }])

    print("========================================================================")
    print("📌 KULLANICI PROFİL BİLGİLERİ (Render PostgreSQL)")
    print("========================================================================")
    display(user_summary_df)

    portfolio_df = pd.DataFrame(results)

    print("\n========================================================================")
    print("📈 CANLI BİST 100 HİSSE PORTFÖYÜ PERFORMANSI")
    print("========================================================================")
    display(portfolio_df)

    print("\n" + "—"*50)
    print(f"💰 TOPLAM HİSSE MALİYETİ  : {total_cost:,.2f} TL")
    print(f"📊 CANLI PORTFÖY DEĞERİ    : {total_current_value:,.2f} TL")
    print(f"🚀 TOPLAM NET KÂR / ZARAR  : {net_pnl:+,.2f} TL (%{total_pnl_pct:+.2f})")
    print("—"*50)

# ==============================================================================
# DEMOYU ÇALIŞTIR
# ==============================================================================
demo_user_id = generate_demo_user()
run_portfolio_demo(demo_user_id)